version: '3'
services:
  scraping-frontend-react:
    container_name: scraping-frontend-react
    hostname: scraping-frontend-react
    build:
     context: .
     dockerfile: Dockerfile
    ports:
      - 8081:8081
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 35M
        reservations:
          cpus: '0.1'
          memory: 30M